### PR TITLE
refactor 1.0

### PR DESCRIPTION
**Pull request by Remi-Gau**
to keep up with reproschema refactoring

### CODE REVIEW

**Comment by satra** [comment]
we should update this to the latest reproschema-ui + release candidate context.

**Comment by Remi-Gau** [comment]
Will work on that this weekend. I got some fMRI experiment coming up and my bandwith is back to being negative.
I am now juggling with too many ~balls~ dynamite sticks. :boom:

**Comment by satra** [comment]
@Remi-Gau - most of this is automatically generated, right? so don't worry about this. let me get your PR to reproschema-py addressed this weekend.

i'm surprised about scanning given the turn in belgium. stay safe please.

**Comment by Remi-Gau** [comment]
> @Remi-Gau - most of this is automatically generated, right? 

Yup just want to make sure that this PR is still "in line" with the release candidate.

> so don't worry about this. let me get your PR to reproschema-py addressed this weekend.

Let me know if I can help I was planning to start playing around with "classes" with this code (subtitle: Remi coming from the world of procedural matlab discovers the beautiful world of object oriented python).

> i'm surprised about scanning given the turn in belgium. stay safe please.

Well starting to pilot some scanns in a couple of weeks. That's the theory. Let's see what reality has to say about it.

**Comment by Remi-Gau** [comment]
OK pyshacl is giving me the green light so things are looking better.

:-)

**Pull request merged**
